name: styled_widget
description: Simplifying your widget tree structure by defining widget using methods. Taking ispiration from CSS and SwiftUI
version: 0.2.2
homepage: https://github.com/ReinBentdal/styled_widget
repository: https://github.com/ReinBentdal/styled_widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter